[package]
name = "util_macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[dev-dependencies]
prettyplease = "0.2"

[dependencies.syn]
version = "2.0"
features = ["full"]
